export const dummyAnswers = [
  { country: 'Andorra', continent: 'Europe', picked: false },
  { country: 'United Arab Emirates', continent: 'Middle East', picked: false },
  { country: 'Afghanistan', continent: 'Middle East', picked: false },
  { country: 'Antigua and Barbuda', continent: 'North America', picked: false },
  { country: 'Anguilla', continent: 'North America', picked: false },
  { country: 'Albania', continent: 'Europe', picked: false },
  { country: 'Armenia', continent: 'Asia', picked: false },
  { country: 'Angola', continent: 'Africa', picked: false },
  { country: 'Argentina', continent: 'South America', picked: false },
  { country: 'American Samoa', continent: 'Oceania', picked: false },

  { country: 'Bosnia and Herzegovina', continent: 'Europe', picked: false },
  { country: 'Barbados', continent: 'North America', picked: false },
  { country: 'Bangladesh', continent: 'Asia', picked: false },
  { country: 'Belgium', continent: 'Europe', picked: false },
  { country: 'Burkina Faso', continent: 'Africa', picked: false },
  { country: 'Bulgaria', continent: 'Europe', picked: false },
  { country: 'Bahrain', continent: 'Middle East', picked: false },
  { country: 'Burundi', continent: 'Africa', picked: false },
  { country: 'Benin', continent: 'Africa', picked: false },
  { country: 'Brunei Darussalam', continent: 'Asia', picked: false },
  { country: 'Bolivia', continent: 'South America', picked: false },
  { country: 'Brazil', continent: 'South America', picked: false },
  { country: 'Botswana', continent: 'Africa', picked: false },
  { country: 'Belarus', continent: 'Europe', picked: false },
  { country: 'Belize', continent: 'South America', picked: false },
  { country: 'Democratic Republic of Congo', continent: 'Africa', picked: false },
  { country: 'Central African Republic', continent: 'Africa', picked: false },
  { country: 'Republic of Congo', continent: 'Africa', picked: false },
  { country: 'Switzerland', continent: 'Europe', picked: false },
  { country: 'Ivory Coast', continent: 'Africa', picked: false },
  { country: 'Chile', continent: 'South America', picked: false },
  { country: 'Cameroon', continent: 'Africa', picked: false },
  { country: 'Colombia', continent: 'South America', picked: false },
  { country: 'Cape Verde', continent: 'Africa', picked: false },
  { country: 'Cyprus', continent: 'Europe', picked: false },

  { country: 'France', continent: 'Europe', picked: false },
  { country: 'Gabon', continent: 'Africa', picked: false },
  { country: 'United Kingdom', continent: 'Europe', picked: false },
  { country: 'Georgia', continent: 'Europe', picked: false },
  { country: 'Ghana', continent: 'Africa', picked: false },
  { country: 'Gambia', continent: 'Africa', picked: false },
  { country: 'Greece', continent: 'Europe', picked: false },
  { country: 'Croatia', continent: 'Europe', picked: false },
  { country: 'Hungary', continent: 'Europe', picked: false },
  { country: 'Ireland', continent: 'Europe', picked: false },
  { country: 'Israel', continent: 'Middle East', picked: false },
  { country: 'Iraq', continent: 'Middle East', picked: false },
  { country: 'Iran', continent: 'Middle East', picked: false },
  { country: 'Iceland', continent: 'Europe', picked: false },
  { country: 'Italy', continent: 'Europe', picked: false },
  { country: 'Jordan', continent: 'Middle East', picked: false },
  { country: 'Kenya', continent: 'Africa', picked: false },
  { country: 'Liberia', continent: 'Africa', picked: false },
  { country: 'Lesotho', continent: 'Africa', picked: false },
  { country: 'Lithuania', continent: 'Europe', picked: false },
  { country: 'Luxembourg', continent: 'Europe', picked: false },
  { country: 'Libya', continent: 'Africa', picked: false },
  { country: 'Morocco', continent: 'Africa', picked: false },
  { country: 'Monaco', continent: 'Europe', picked: false },
  { country: 'Madagascar', continent: 'Africa', picked: false },
  { country: 'Mali', continent: 'Africa', picked: false },
  { country: 'Mauritania', continent: 'Africa', picked: false },
  { country: 'Malta', continent: 'Europe', picked: false },
  { country: 'Mozambique', continent: 'Africa', picked: false },
  { country: 'Namibia', continent: 'Africa', picked: false },
  { country: 'Niger', continent: 'Africa', picked: false },
  { country: 'Nigeria', continent: 'Africa', picked: false },
  { country: 'Netherlands', continent: 'Europe', picked: false },
  { country: 'Norway', continent: 'Europe', picked: false },
  { country: 'Oman', continent: 'Middle East', picked: false },
  { country: 'Peru', continent: 'South America', picked: false },
  { country: 'Palestine', continent: 'Middle East', picked: false },
  { country: 'Portugal', continent: 'Europe', picked: false },
  { country: 'Qatar', continent: 'Middle East', picked: false },
  { country: 'Romania', continent: 'Europe', picked: false },
  { country: 'Serbia', continent: 'Europe', picked: false },

  { country: 'Togo', continent: 'Africa', picked: false },
  { country: 'Turkey', continent: 'Middle East', picked: false },
  { country: 'Tanzania', continent: 'Africa', picked: false },
  { country: 'Ukraine', continent: 'Europe', picked: false },
  { country: 'Uganda', continent: 'Africa', picked: false },
  { country: 'Uruguay', continent: 'South America', picked: false },
  { country: 'Vatican', continent: 'Europe', picked: false },
  { country: 'Venezuela', continent: 'South America', picked: false },
  { country: 'Yemen', continent: 'Middle East', picked: false },
  { country: 'Zambia', continent: 'Africa', picked: false },
  { country: 'Zimbabwe', continent: 'Africa', picked: false },
  { country: 'Bermuda', continent: 'North America', picked: false },
  { country: 'Bahamas', continent: 'North America', picked: false },
  { country: 'Bhutan', continent: 'Asia', picked: false },
  { country: 'Canada', continent: 'North America', picked: false },
  { country: 'China', continent: 'Asia', picked: false },
  { country: 'Costa Rica', continent: 'Central America', picked: false },
  { country: 'Cuba', continent: 'North America', picked: false },
  { country: 'Curaçao', continent: 'North America', picked: false },
  { country: 'Dominica', continent: 'North America', picked: false },
  { country: 'Dominican Republic', continent: 'North America', picked: false },
  { country: 'Algeria', continent: 'Africa', picked: false },
  { country: 'Ecuador', continent: 'South America', picked: false },
  { country: 'Estonia', continent: 'Europe', picked: false },
  { country: 'Fiji', continent: 'Oceania', picked: false },
  { country: 'Micronesia', continent: 'Oceania', picked: false },
  { country: 'Grenada', continent: 'North America', picked: false },
  { country: 'French Guiana', continent: 'South America', picked: false },
  { country: 'Greenland', continent: 'North America', picked: false },
  { country: 'Guinea', continent: 'Africa', picked: false },
  { country: 'Equatorial Guinea', continent: 'Africa', picked: false },

  { country: 'Kiribati', continent: 'Oceania', picked: false },
  { country: 'Comoros', continent: 'Africa', picked: false },
  { country: 'St Kitts and Nevis', continent: 'North America', picked: false },
  { country: 'North Korea', continent: 'Asia', picked: false },
  { country: 'South Korea', continent: 'Asia', picked: false },
  { country: 'Kosovo', continent: 'Europe', picked: false },
  { country: 'Kuwait', continent: 'Middle East', picked: false },
  { country: 'Cayman Islands', continent: 'North America', picked: false },
  { country: 'Kazakhstan', continent: 'Asia', picked: false },
  { country: 'Laos', continent: 'Asia', picked: false },
  { country: 'Lebanon', continent: 'Middle East', picked: false },
  { country: 'St Lucia', continent: 'North America', picked: false },
  { country: 'Liechtenstein', continent: 'Liechtenstein', picked: false },
  { country: 'Sri Lanka', continent: 'Asia', picked: false },
  { country: 'Latvia', continent: 'Europe', picked: false },
  { country: 'Moldova', continent: 'Europe', picked: false },
  { country: 'Montenegro', continent: 'Europe', picked: false },
  { country: 'Macedonia', continent: 'Europe', picked: false },
  { country: 'Macau', continent: 'Asia', picked: false },
  { country: 'Myanmar', continent: 'Asia', picked: false },
  { country: 'Mongolia', continent: 'Asia', picked: false },
  { country: 'Martinique', continent: 'Africa', picked: false },
  { country: 'Mauritius', continent: 'Africa', picked: false },
  { country: 'Maldives', continent: 'Asia', picked: false },
  { country: 'Malawi', continent: 'Africa', picked: false },
  { country: 'Mexico', continent: 'Central America', picked: false },
  { country: 'Malaysia', continent: 'Asia', picked: false },
  { country: 'Nicaragua', continent: 'Central America', picked: false },
  { country: 'Nepal', continent: 'Asia', picked: false },
  { country: 'Nauru', continent: 'Oceania', picked: false },
  { country: 'New Zealand', continent: 'Oceania', picked: false },
  { country: 'Panama', continent: 'Central America', picked: false },
  { country: 'French Polynesia', continent: 'Oceania', picked: false },
  { country: 'Papua New Guinea', continent: 'Oceania', picked: false },
  { country: 'Philippines', continent: 'Asia', picked: false },
  { country: 'Pakistan', continent: 'Asia', picked: false },
  { country: 'Poland', continent: 'Europe', picked: false },
  { country: 'Palau', continent: 'Oceania', picked: false },
  { country: 'Paraguay', continent: 'South America', picked: false },
  { country: 'Rwanda', continent: 'Africa', picked: false },
  { country: 'Solomon Islands', continent: 'Oceania', picked: false },
  { country: 'Seychelles', continent: 'Asia', picked: false },
  { country: 'Sudan', continent: 'Africa', picked: false },
  { country: 'Singapore', continent: 'Asia', picked: false },
  { country: 'Sierra Leone', continent: 'Africa', picked: false },
  { country: 'Suriname', continent: 'South America', picked: false },
  { country: 'Sao Tome and Principe', continent: 'Africa', picked: false },
  { country: 'El Salvador', continent: 'Central America', picked: false },
  { country: 'Turks and Caicos', continent: 'North America', picked: false },

  { country: 'Taiwan', continent: 'Asia', picked: false },
  { country: 'United States', continent: 'North America', picked: false },
  { country: 'Uzbekistan', continent: 'Asia', picked: false },
  { country: 'St Vincent and the Grenadines', continent: 'North America', picked: false },
  { country: 'Vietnam', continent: 'Asia', picked: false },
  { country: 'Samoa', continent: 'Oceania', picked: false },
  { country: 'South Africa', continent: 'Africa', picked: false },
];
