export const permittedAnswers = [
  { country: 'Andorra', continent: 'Europe' },
  { country: 'United Arab Emirates', continent: 'Middle East' },
  { country: 'Afghanistan', continent: 'Middle East' },
  { country: 'Antigua and Barbuda', continent: 'North America' },
  { country: 'Anguilla', continent: 'North America' },
  { country: 'Albania', continent: 'Europe' },
  { country: 'Armenia', continent: 'Asia' },
  { country: 'Angola', continent: 'Africa' },
  { country: 'Argentina', continent: 'South America' },
  { country: 'American Samoa', continent: 'Oceania' },
  { country: 'Austria', continent: 'Europe' },
  { country: 'Australia', continent: 'Oceania' },
  { country: 'Aruba', continent: 'South America' },
  { country: 'Azerbaijan', continent: 'Asia' },
  { country: 'Bosnia and Herzegovina', continent: 'Europe' },
  { country: 'Barbados', continent: 'North America' },
  { country: 'Bangladesh', continent: 'Asia' },
  { country: 'Belgium', continent: 'Europe' },
  { country: 'Burkina Faso', continent: 'Africa' },
  { country: 'Bulgaria', continent: 'Europe' },
  { country: 'Bahrain', continent: 'Middle East' },
  { country: 'Burundi', continent: 'Africa' },
  { country: 'Benin', continent: 'Africa' },
  { country: 'Saint Barthelemy', continent: 'North America' },
  { country: 'Brunei Darussalam', continent: 'Asia' },
  { country: 'Bolivia', continent: 'South America' },
  { country: 'Brazil', continent: 'South America' },
  { country: 'Botswana', continent: 'Africa' },
  { country: 'Belarus', continent: 'Europe' },
  { country: 'Belize', continent: 'South America' },
  { country: 'Democratic Republic of Congo', continent: 'Africa' },
  { country: 'Central African Republic', continent: 'Africa' },
  { country: 'Republic of Congo', continent: 'Africa' },
  { country: 'Switzerland', continent: 'Europe' },
  { country: 'Ivory Coast', continent: 'Africa' },
  { country: 'Chile', continent: 'South America' },
  { country: 'Cameroon', continent: 'Africa' },
  { country: 'Colombia', continent: 'South America' },
  { country: 'Cape Verde', continent: 'Africa' },
  { country: 'Cyprus', continent: 'Europe' },
  { country: 'Czech Republic', continent: 'Europe' },
  { country: 'Germany', continent: 'Europe' },
  { country: 'Djibouti', continent: 'Africa' },
  { country: 'Denmark', continent: 'Europe' },
  { country: 'Egypt', continent: 'Africa' },
  { country: 'Western Sahara', continent: 'Africa' },
  { country: 'Eritrea', continent: 'Africa' },
  { country: 'Spain', continent: 'Europe' },
  { country: 'Ethiopia', continent: 'Africa' },
  { country: 'Finland', continent: 'Europe' },
  { country: 'France', continent: 'Europe' },
  { country: 'Gabon', continent: 'Africa' },
  { country: 'United Kingdom', continent: 'Europe' },
  { country: 'Georgia', continent: 'Europe' },
  { country: 'Guernsey', continent: 'Europe' },
  { country: 'Ghana', continent: 'Africa' },
  { country: 'Gambia', continent: 'Africa' },
  { country: 'Greece', continent: 'Europe' },
  { country: 'Croatia', continent: 'Europe' },
  { country: 'Hungary', continent: 'Europe' },
  { country: 'Ireland', continent: 'Europe' },
  { country: 'Israel', continent: 'Middle East' },
  { country: 'Isle of Man', continent: 'Europe' },
  { country: 'Iraq', continent: 'Middle East' },
  { country: 'Iran', continent: 'Middle East' },
  { country: 'Iceland', continent: 'Europe' },
  { country: 'Italy', continent: 'Europe' },
  { country: 'Jersey', continent: 'Europe' },
  { country: 'Jordan', continent: 'Middle East' },
  { country: 'Kenya', continent: 'Africa' },
  { country: 'Liberia', continent: 'Africa' },
  { country: 'Lesotho', continent: 'Africa' },
  { country: 'Lithuania', continent: 'Europe' },
  { country: 'Luxembourg', continent: 'Europe' },
  { country: 'Libya', continent: 'Africa' },
  { country: 'Morocco', continent: 'Africa' },
  { country: 'Monaco', continent: 'Europe' },
  { country: 'Madagascar', continent: 'Africa' },
  { country: 'Mali', continent: 'Africa' },
  { country: 'Mauritania', continent: 'Africa' },
  { country: 'Malta', continent: 'Europe' },
  { country: 'Mozambique', continent: 'Africa' },
  { country: 'Namibia', continent: 'Africa' },
  { country: 'Niger', continent: 'Africa' },
  { country: 'Nigeria', continent: 'Africa' },
  { country: 'Netherlands', continent: 'Europe' },
  { country: 'Norway', continent: 'Europe' },
  { country: 'Oman', continent: 'Middle East' },
  { country: 'Peru', continent: 'South America' },
  { country: 'Palestinian Territories', continent: 'Middle East' },
  { country: 'Portugal', continent: 'Europe' },
  { country: 'Qatar', continent: 'Middle East' },
  { country: 'Romania', continent: 'Europe' },
  { country: 'Serbia', continent: 'Europe' },
  { country: 'Russia', continent: 'Europe' },
  { country: 'Saudi Arabia', continent: 'Middle East' },
  { country: 'Sweden', continent: 'Europe' },
  { country: 'Slovenia', continent: 'Europe' },
  { country: 'Slovakia', continent: 'Europe' },
  { country: 'San Marino', continent: 'Europe' },
  { country: 'Senegal', continent: 'Africa' },
  { country: 'Somalia', continent: 'Africa' },
  { country: 'South Sudan', continent: 'Africa' },
  { country: 'Syria', continent: 'Middle East' },
  { country: 'Swaziland', continent: 'Europe' },
  { country: 'Chad', continent: 'Africa' },
  { country: 'Togo', continent: 'Africa' },
  { country: 'Turkey', continent: 'Middle East' },
  { country: 'Tanzania', continent: 'Africa' },
  { country: 'Ukraine', continent: 'Europe' },
  { country: 'Uganda', continent: 'Africa' },
  { country: 'Uruguay', continent: 'South America' },
  { country: 'Vatican', continent: 'Europe' },
  { country: 'Venezuela', continent: 'South America' },
  { country: 'Yemen', continent: 'Middle East' },
  { country: 'Zambia', continent: 'Africa' },
  { country: 'Zimbabwe', continent: 'Africa' },
  { country: 'Bermuda', continent: 'North America' },
  { country: 'Bahamas', continent: 'North America' },
  { country: 'Bhutan', continent: 'Asia' },
  { country: 'Canada', continent: 'North America' },
  { country: 'China', continent: 'Asia' },
  { country: 'Costa Rica', continent: 'Central America' },
  { country: 'Cuba', continent: 'North America' },
  { country: 'Curaçao', continent: 'North America' },
  { country: 'Dominica', continent: 'North America' },
  { country: 'Dominican Republic', continent: 'North America' },
  { country: 'Algeria', continent: 'Africa' },
  { country: 'Ecuador', continent: 'South America' },
  { country: 'Estonia', continent: 'Europe' },
  { country: 'Fiji', continent: 'Oceania' },
  { country: 'Federated States of Micronesia', continent: 'Oceania' },
  { country: 'Grenada', continent: 'North America' },
  { country: 'French Guiana', continent: 'South America' },
  { country: 'Gibraltar', continent: 'Europe' },
  { country: 'Greenland', continent: 'North America' },
  { country: 'Guinea', continent: 'Africa' },
  { country: 'Equatorial Guinea', continent: 'Africa' },
  { country: 'Guatemala', continent: 'Central America' },
  { country: 'Guinea-Bissau', continent: 'Africa' },
  { country: 'Guyana', continent: 'South America' },
  { country: 'Hong Kong', continent: 'Asia' },
  { country: 'Honduras', continent: 'Central America' },
  { country: 'Haiti', continent: 'North America' },
  { country: 'Indonesia', continent: 'Asia' },
  { country: 'India', continent: 'Asia' },
  { country: 'Jamaica', continent: 'North America' },
  { country: 'Japan', continent: 'Asia' },
  { country: 'Kyrgyzstan', continent: 'Asia' },
  { country: 'Cambodia', continent: 'Asia' },
  { country: 'Kiribati', continent: 'Oceania' },
  { country: 'Comoros', continent: 'Africa' },
  { country: 'Saint Kitts and Nevis', continent: 'North America' },
  { country: 'North Korea', continent: 'Asia' },
  { country: 'South Korea', continent: 'Asia' },
  { country: 'Kosovo', continent: 'Europe' },
  { country: 'Kuwait', continent: 'Middle East' },
  { country: 'Cayman Islands', continent: 'North America' },
  { country: 'Kazakhstan', continent: 'Asia' },
  { country: "Lao People's Democratic Republic", continent: 'Asia' },
  { country: 'Lebanon', continent: 'Middle East' },
  { country: 'Saint Lucia', continent: 'North America' },
  { country: 'Liechtenstein', continent: 'Liechtenstein' },
  { country: 'Sri Lanka', continent: 'Asia' },
  { country: 'Latvia', continent: 'Europe' },
  { country: 'Moldova', continent: 'Europe' },
  { country: 'Montenegro', continent: 'Europe' },
  { country: 'Macedonia', continent: 'Europe' },
  { country: 'Macau', continent: 'Asia' },
  { country: 'Myanmar', continent: 'Asia' },
  { country: 'Mongolia', continent: 'Asia' },
  { country: 'Martinique', continent: 'Africa' },
  { country: 'Mauritius', continent: 'Africa' },
  { country: 'Maldives', continent: 'Asia' },
  { country: 'Malawi', continent: 'Africa' },
  { country: 'Mexico', continent: 'Central America' },
  { country: 'Malaysia', continent: 'Asia' },
  { country: 'Nicaragua', continent: 'Central America' },
  { country: 'Nepal', continent: 'Asia' },
  { country: 'Nauru', continent: 'Oceania' },
  { country: 'New Zealand', continent: 'Oceania' },
  { country: 'Panama', continent: 'Central America' },
  { country: 'French Polynesia', continent: 'Oceania' },
  { country: 'Papua New Guinea', continent: 'Oceania' },
  { country: 'Philippines', continent: 'Asia' },
  { country: 'Pakistan', continent: 'Asia' },
  { country: 'Poland', continent: 'Europe' },
  { country: 'Puerto Rico', continent: 'Central America' },
  { country: 'Palau', continent: 'Oceania' },
  { country: 'Paraguay', continent: 'South America' },
  { country: 'Rwanda', continent: 'Africa' },
  { country: 'Solomon Islands', continent: 'Oceania' },
  { country: 'Seychelles', continent: 'Asia' },
  { country: 'Sudan', continent: 'Africa' },
  { country: 'Singapore', continent: 'Asia' },
  { country: 'Sierra Leone', continent: 'Africa' },
  { country: 'Suriname', continent: 'South America' },
  { country: 'Sao Tome and Principe', continent: 'Africa' },
  { country: 'El Salvador', continent: 'Central America' },
  { country: 'Turks and Caicos Islands', continent: 'North America' },
  { country: 'Thailand', continent: 'Asia' },
  { country: 'Tajikistan', continent: 'Asia' },
  { country: 'Timor-Leste', continent: 'Africa' },
  { country: 'Turkmenistan', continent: 'Asia' },
  { country: 'Tunisia', continent: 'Africa' },
  { country: 'Tonga', continent: 'Africa' },
  { country: 'Trinidad and Tobago', continent: 'South America' },
  { country: 'Tuvalu', continent: 'Oceania' },
  { country: 'Taiwan', continent: 'Asia' },
  { country: 'United States', continent: 'North America' },
  { country: 'Uzbekistan', continent: 'Asia' },
  { country: 'Saint Vincent and the Grenadines', continent: 'North America' },
  { country: 'Vietnam', continent: 'Asia' },
  { country: 'Samoa', continent: 'Oceania' },
  { country: 'South Africa', continent: 'Africa' },
];
